name: Update IOCs
on:
  schedule:
    - cron: '0 * * * *'  # Hourly updates
  workflow_dispatch:     # Manual trigger

jobs:
  update:
    runs-on: ubuntu-linux-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Run aggregator
        run: python backend/aggregator.py

      - name: Refresh symlink
        run: |
          # Remove existing symlink if exists
          [ -L docs ] && rm docs || true
          # Create fresh symlink
          ln -s frontend docs
          # Verify symlink
          ls -l docs

      - name: Commit and Push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add docs frontend/iocs.json
          git diff --cached --quiet || (git commit -m "Auto-update IOCs [$(date +'%Y-%m-%d %H:%M UTC')]" && 
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main)