name: Update IOCs
on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:     # Manual trigger option

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Run aggregator
        run: python backend/aggregator.py

      - name: Sync to docs folder
        run: |
          mkdir -p docs
          cp -r frontend/* docs/
          # Preserve .nojekyll if exists
          [ -f frontend/.nojekyll ] && cp frontend/.nojekyll docs/

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add docs frontend/iocs.json
          git diff --cached --quiet || (git commit -m "Auto-update IOCs [$(date +'%Y-%m-%d %H:%M UTC')]" && 
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main)