name: Update IOCs Hourly
on:
  schedule:
    - cron: '0 * * * *'  # Runs at minute 0 of every hour
  workflow_dispatch:     # Manual trigger option

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper git history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Run aggregator
        run: python backend/aggregator.py

      - name: Commit and Push Changes
        if: success()  # Only run if previous steps succeeded
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add frontend/iocs.json
          # Only commit if there are changes
          git diff --cached --quiet || (git commit -m "Auto-update IOCs [$(date +'%Y-%m-%d %H:%M UTC')]" && 
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main)